# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      bulankin.vs@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    env:
      global:
        - CODECOV_TOKEN="fb0fda32-e31a-40a3-a691-62bfe78997f6"